######################################################################
##
## Filename: P1e1_tb.udo
## Created on: Wed Feb 03 10:19:22 Hora estándar romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
