######################################################################
##
## Filename: MicroMIPSTb.udo
## Created on: Wed Apr 20 9:58:40 Hora de verano romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
