######################################################################
##
## Filename: RegsTb.udo
## Created on: Wed Feb 17 10:17:11 Hora estándar romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
