######################################################################
##
## Filename: ContadorTb.udo
## Created on: Wed Feb 10 10:04:45 Hora estándar romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
