######################################################################
##
## Filename: Deco3a8Reg.udo
## Created on: Wed Feb 10 8:59:16 Hora estándar romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
