######################################################################
##
## Filename: MicroMIPSTb.udo
## Created on: Wed Apr 13 10:17:56 Hora de verano romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
