######################################################################
##
## Filename: ALUMIPSTb.udo
## Created on: Wed Mar 02 10:50:42 Hora estándar romance 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
